// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcu7zfNNjfH_IUVnOPUrveADtIocYZ5zw',
    appId: '1:582454000506:web:daf9fb14a912c47e4db4c3',
    messagingSenderId: '582454000506',
    projectId: 'bluesky-d9c9a',
    authDomain: 'bluesky-d9c9a.firebaseapp.com',
    storageBucket: 'bluesky-d9c9a.appspot.com',
    measurementId: 'G-DG8KCCZE8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUTWxHuGz7yABEUdu9WSOGo8lNn1Cl9G4',
    appId: '1:582454000506:android:791cca76456c33054db4c3',
    messagingSenderId: '582454000506',
    projectId: 'bluesky-d9c9a',
    storageBucket: 'bluesky-d9c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu7tmqaJtROfVS_IwcJ6vsvoCAq8-dc50',
    appId: '1:582454000506:ios:5bdda3ebd8703b7d4db4c3',
    messagingSenderId: '582454000506',
    projectId: 'bluesky-d9c9a',
    storageBucket: 'bluesky-d9c9a.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu7tmqaJtROfVS_IwcJ6vsvoCAq8-dc50',
    appId: '1:582454000506:ios:65cba724d4c3d23f4db4c3',
    messagingSenderId: '582454000506',
    projectId: 'bluesky-d9c9a',
    storageBucket: 'bluesky-d9c9a.appspot.com',
    iosBundleId: 'com.example.book.RunnerTests',
  );
}
